### ISSUE TITLE
Include json in error 

### ISSUE THREAD

**Issue by peteruithoven** [rspective/voucherify-nodejs-sdk#42]
Currently when a request like redeem fails I get an error which `message` is for example: 
```
Unexpected status code: 404 - Details: {"code":404,"message":"Resource not found","details":"Cannot find Voucher with code: onbacker34rCD41S","key":"resource_not_found"}
```
I'd really like to reuse that piece of json at the end as an json error response, making it easily parseble by my client side code. 
Would it be possible to add that raw json as extra property to the error object?

**Comment by tpindel** [comment]
@peteruithoven 
Hi there! Sure we can do it. We will improve this week. If it is too late, you can prepare PR to this repository.

**Comment by bandraszyk** [comment]
@peteruithoven @tpindel The following PR should resolve this: #43 
I kept `toString` method so when you do `console.log("%s", error);` all should work the same way.

**Comment by tpindel** [comment]
@bandraszyk thanks! 👍  Package released : https://www.npmjs.com/package/voucherify

@peteruithoven Will this work for you?

**Comment by peteruithoven** [comment]
Awesome and super quick, thanks @bandraszyk!
